[project]
name = "introduce-defects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "networkx>=3.5",
    "numpy>=2.2.6",
    "scipy>=1.15.3",
    "tabulate>=0.9.0",
]
